### ISSUE TITLE
IndexError: No item with that key

### ISSUE THREAD

**Issue by ItsAmirAT** [hokireceh/blum#1]
Traceback (most recent call last):                                                File "/root/blum/bot.py", line 647, in <module>                                   asyncio.run(main())                                                           File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run                    return loop.run_until_complete(main)                                          File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/blum/bot.py", line 625, in main
    res = await BlumTod(
  File "/root/blum/bot.py", line 239, in start
    result = await get_by_id(uid)
  File "/root/blum/models.py", line 76, in get_by_id
    "useragent": result["useragent"],
IndexError: No item with that key

**Comment by hokireceh** [comment]
git pull , n join my chanel
